<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * This file is generated by Webpack, do not edit it directly.
 */

return [
	'handle' => 'elementor-packages-editor',
	'src' => plugins_url( '/', __FILE__ ) . 'editor{{MIN_SUFFIX}}.js',
	'i18n' => [
		'domain' => 'elementor',
		'replace_requested_file' => true,
	],
	'type' => 'app',
	'deps' => [
		'elementor-packages-locations',
		'elementor-packages-store',
		'elementor-packages-ui',
		'elementor-packages-v1-adapters',
		'react',
		'react-dom',
		'wp-i18n',
	],
];
