<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * This file is generated by Webpack, do not edit it directly.
 */

add_filter( 'elementor/editor-v2/packages/config', function( $data ) {

	$data['elementor-packages-documents'] = require __DIR__ . '/documents.asset.php';

	$data['elementor-packages-documents-ui'] = require __DIR__ . '/documents-ui.asset.php';

	$data['elementor-packages-editor'] = require __DIR__ . '/editor.asset.php';

	$data['elementor-packages-elements-panel'] = require __DIR__ . '/elements-panel.asset.php';

	$data['elementor-packages-finder'] = require __DIR__ . '/finder.asset.php';

	$data['elementor-packages-help'] = require __DIR__ . '/help.asset.php';

	$data['elementor-packages-history'] = require __DIR__ . '/history.asset.php';

	$data['elementor-packages-icons'] = require __DIR__ . '/icons.asset.php';

	$data['elementor-packages-locations'] = require __DIR__ . '/locations.asset.php';

	$data['elementor-packages-recently-edited'] = require __DIR__ . '/recently-edited.asset.php';

	$data['elementor-packages-responsive'] = require __DIR__ . '/responsive.asset.php';

	$data['elementor-packages-site-settings'] = require __DIR__ . '/site-settings.asset.php';

	$data['elementor-packages-store'] = require __DIR__ . '/store.asset.php';

	$data['elementor-packages-structure'] = require __DIR__ . '/structure.asset.php';

	$data['elementor-packages-theme-builder'] = require __DIR__ . '/theme-builder.asset.php';

	$data['elementor-packages-top-bar'] = require __DIR__ . '/top-bar.asset.php';

	$data['elementor-packages-user-preferences'] = require __DIR__ . '/user-preferences.asset.php';

	$data['elementor-packages-v1-adapters'] = require __DIR__ . '/v1-adapters.asset.php';

	$data['elementor-packages-ui'] = require __DIR__ . '/ui.asset.php';

	return $data;
} );
